### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by WolfangAukang** [jbensmann/mouseless#13]
This is a very trivial request. The reason is because I am packaging this for Nix and generally I need to reference a license to it.

**Comment by benjaminbhollon** [comment]
Ooh, packaged for nix would be great. Would there be some way to run it without sudo? I don't think the way referenced in the README would work on NixOS.

Just discovered this yesterday and have spent the day customizing all my keybindings; I love it!

**Comment by WolfangAukang** [comment]
> Ooh, packaged for nix would be great. Would there be some way to run it without sudo? I don't think the way referenced in the README would work on NixOS.

Creating a module where you can specify the user(s) might be an option, as you have the capability of adding the udev rules through it.

**Comment by jbensmann** [comment]
Yeah I was not sure which license to choose, after some research I think MIT is fine, I've just added it.

**Comment by WolfangAukang** [comment]
Thanks a lot!

**Comment by benjaminbhollon** [comment]
I approve of the decision. ;)

Copyleft (ie GPL and friends) may have worked well too, but could cause problems if people wanted to use this as a dependency of some sort.
