### ISSUE TITLE
Binding `\`

### ISSUE THREAD

**Issue by Victor239** [jbensmann/mouseless#14]
Is it possible to bind the `\` key? If so what is the text value for it, because `\` and `backslash` don't work.

**Comment by Victor239** [comment]
I found https://github.com/jbensmann/mouseless/blob/main/keydefs.go but `backslash` still doesn't work for me. Any way to troubleshoot this?

**Comment by jbensmann** [comment]
You can run mouseless with the flag `--debug`, then it will show the names of the keys that you press, which looks like this when I press the backslash key (which is one of the keys next to Enter):
```
DEBU[0016] Pressed:  backslash (43)
```
So `backslash` should be right, could you share the logs if it also says `backslash` for you but still does not work?

**Comment by Victor239** [comment]
Ah it's `102nd` key for me. Google says it's for `Keyboard Non-US \ and |` which makes sense. Thanks for the help!
```
DEBU[0005] Pressed:  102nd (86)                         
DEBU[0005] Read from queue: {86 true false}             
DEBU[0005] Executing main.KeyBinding: {BaseBinding:{} KeyCombo:[86]} 
DEBU[0005] Keyboard: pressing 86                        
\DEBU[0005] Released: 102nd (86)                         
DEBU[0005] Read from queue: {86 false false}            
DEBU[0005] Keyboard: releasing 86                       
DEBU[0005] Executing main.KeyBinding: {BaseBinding:{} KeyCombo:[86]}
```

**Comment by jbensmann** [comment]
You're welcome 🙂
