### ISSUE TITLE
Version not incremented

### ISSUE THREAD

**Issue by benjaminbhollon** [jbensmann/mouseless#15]
Running mouseless  -v on the latest release's binary gets me 0.1.0. I'm not sure if this is just that that command wasn't updated properly or if the binary hasn't been updated?

**Comment by jbensmann** [comment]
I only forgot to update the version in one place, otherwise the binaries are up to date. Thanks for reporting, I will correct it soon.

**Comment by jbensmann** [comment]
It is now corrected in version 0.1.4
