### ISSUE TITLE
Can't run without sudo command even with udev rule added

### ISSUE THREAD

**Issue by SeafoamGreeen** [jbensmann/mouseless#2]
Hey, thanks for the cool program! I'm having troubles making mouseless run without sudo privileges. I ran the command on the readme, rebooted, and when trying to run mouseless it gave me this error.

**ERRO[0000] Failed to init the virtual mouse: could not create relative axis input device: could not open device file**

Then I tried to manually add the rules, this is the file. 99-seafoam.rules (user is seafoam)
`KERNEL=="input", GROUP="seafoam", MODE:="0660"
KERNEL=="event*", GROUP="seafoam", NAME="input/%k", MODE="660"
`
after rebooting,  it kept giving me the same error as before. am I missing something?

**Comment by jbensmann** [comment]
Hey, looks like there is a mistake in the README, it must be `KERNEL=="uinput"` instead of `KERNEL=="input"`, thanks for spotting this, I will correct it. Let me know if it works with the correction.

**Comment by SeafoamGreeen** [comment]
Hey, yeah it worked, but also I had to do one extra step to get it working, I followed this instructions to make the udev rules change permission.
Don't know if it's a common problem but I thought it's worth mentioning if someone else can't get their udev rules to change.
https://github.com/chrippa/ds4drv/issues/93#issuecomment-265300511
The issue is fixed

**Comment by gotbletu** [comment]
same issue, maybe add that in the frontpage so others dont gotta dig thru these github issues pages.
anyways works now without sudo

`echo "uinput" | sudo tee /etc/modules-load.d/uinput.conf`

**Comment by jbensmann** [comment]
Thanks I have added it to the README
