### ISSUE TITLE
Three commands sequentially?

### ISSUE THREAD

**Issue by I03D** [jbensmann/mouseless#21]
I was pleased that there is a meta action "multi", but I could not cover more than two actions (even by embedding one operator into another).

Thank you for getting rid of the mouse!

**Comment by jbensmann** [comment]
Yeah currently the multi binding only allows two  actions, and one cannot embed the meta actions into each other, but I think there is no reason why the multi should not accept any number of actions, I will add that.

**Comment by I03D** [comment]
I don't remember exactly, but then I probably didn't know about such abbreviated entries as "alt+a". :P
