### ISSUE TITLE
Failed to read the config file: failed to parse layer 2 : failed to parse the key '_': neither an integer nor a key alias

### ISSUE THREAD

**Issue by Elkellympia** [jbensmann/mouseless#26]
## When running `sudo mouseless -d --config ~/.config/mouseless/config.yaml` the output is the following:
```
DEBU[0000] Using config file: /home/arcus/.config/mouseless/config.yaml
ERRO[0000] Failed to read the config file: failed to parse layer 2 : failed to parse the key '_': neither an integer nor a key alias
ERRO[0000] Exiting
```
My system is arch very minimal, i may not have a package needed to run the binary.
Yes, the binary is in the path, the config file is correctly written

**Comment by benjaminbhollon** [comment]
mouseless doesn't consider underscores as "_" but as a shift key plus "minus". That's probably what's happening here.

To see how mousless interprets a key you can run it with the --debug flag and then press that key.

**Comment by jbensmann** [comment]
Sorry for the late response, the `_` key is a new feature to match all keys that are not mapped, it is not included in the latest release yet, I will build a new release soon.

**Comment by jbensmann** [comment]
A new release has been created.
