### ISSUE TITLE
Tank you SO much!

### ISSUE THREAD

**Issue by remembertoremind** [jbensmann/mouseless#27]
Not an issue. Just wanted to say thanks! I've been addicted to trackpoints for many years now and all other keyboards are worthless to me. I've tried qmk-compatible keyboards but they are really tedious to configure. `mouseless` fixes these problems and I can now start playing with new keyboards :D!

**Comment by jbensmann** [comment]
Thank you for the comment! :heart: 
It's really nice to hear when the program is valuable to someone else, that's why I am putting this out into the public.
