### ISSUE TITLE
Possible to use XF86Back or something similar

### ISSUE THREAD

**Issue by remembertoremind** [jbensmann/mouseless#30]
I have setup some control for going foward/back in my browser, but often use different browsers means that it only works on one and not both.

Getting "Back" or "XF86Back" would solve that. I have tried both and also "button back" but none of then are recognised by mouseless.

**Comment by jbensmann** [comment]
I think simply `back` (lowercase) is the right key, I found that by looking through the keydefs.go since I do not have that key on my keyboard to check, and it's working in Firefox and Chrome.

**Comment by remembertoremind** [comment]
I was sure I had tried everything. I even made sure before I created this post. Thansk! :)
