### ISSUE TITLE
failed to run without root privileges

### ISSUE THREAD

**Issue by zerobikappa** [jbensmann/mouseless#31]
I have tried to add udev rule:
```
echo "KERNEL==\"uinput\", GROUP=\"$USER\", MODE:=\"0660\"
KERNEL==\"event*\", GROUP=\"$USER\", NAME=\"input/%k\", MODE=\"660\"" \
| sudo tee /etc/udev/rules.d/99-$USER.rules
```
and add my username into `input` group:
```
sudo usermod -aG input $USER
```
However `mouseless` still failed to launch with below message:
```
ERRO[0000] Failed to init the virtual mouse: could not create relative axis input device: could not open device file
ERRO[0000] Exiting
```
my system details:

Operating System: Arch Linux 
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.106.0
Qt Version: 5.15.9
Kernel Version: 6.3.5-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-3770 CPU @ 3.40GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 4000
Manufacturer: Intel
Product Name: B75A

**Comment by remembertoremind** [comment]
Could you post your config and the command you use to start mouseless? I had the same error which was caused by my failing to set the config correctly. Check my [config](https://github.com/jbensmann/mouseless/issues/25#issuecomment-1555994102).

**Comment by remembertoremind** [comment]
Yeah, that is weird. Did you try with rebooting?

Does /etc/udev/rules.d have to file you created and does it have the right content?

```
KERNEL=="uinput", GROUP="YOURUSER", MODE:="0660"
KERNEL=="event*", GROUP="YOURUSER", NAME="input/%k", MODE="660"
```

**Comment by zerobikappa** [comment]
> Yeah, that is weird. Did you try with rebooting?
> 
> Does /etc/udev/rules.d have the file you created and does it have the right content?
> 
> ```
> KERNEL=="uinput", GROUP="YOURUSER", MODE:="0660"
> KERNEL=="event*", GROUP="YOURUSER", NAME="input/%k", MODE="660"
> ```

Thank you, you solved my problem.

With my another archlinux machine, I only added my user account into `input` group then I can run `mouseless` without root privilege. I did not realized that I should also add udev rule to get permission for virtual device(`/dev/uinput`).

After some checking, I found that it was because I installed `steam` in this machine and `steam` already included this rule in `/usr/lib/udev/rules.d/70-steam-input.rules` :
```bash
KERNEL=="uinput", SUBSYSTEM=="misc", OPTIONS+="static_node=uinput", TAG+="uaccess", OPTIONS+="static_node=uinput"
```

Seem it would grant permission automatically to all logged-in users.

**Comment by remembertoremind** [comment]
Arh! Interesting. I also had some issues dealing with both Ubuntu and Arch, and figured it out at some point but never wrote down what I did to fix it :)
