### ISSUE TITLE
Ability to use a regular mouse while mouseless is running?

### ISSUE THREAD

**Issue by ArijanJ** [jbensmann/mouseless#35]
When I run mouseless, I cannot use my regular mouse. I'd like to use this tool as a convenience, but still have access to my mouse. Is this possible?

**Comment by jbensmann** [comment]
Hi, usually the regular mouse should still work, maybe mouseless detects it as keyboard and reads from it too.
Have you specified a device in the configuration file? If not, you could try to add your keyboard there, so that mouseless does not try to find the keyboard devices on its own.

**Comment by ArijanJ** [comment]
> Hi, usually the regular mouse should still work, maybe mouseless detects it as keyboard and reads from it too. Have you specified a device in the configuration file? If not, you could try to add your keyboard there, so that mouseless does not try to find the keyboard devices on its own.

Yes, that was the problem, thank you!
