### ISSUE TITLE
Question regarding: mapping to Numpad Keys

### ISSUE THREAD

**Issue by mostafa20220** [jbensmann/mouseless#37]
I am trying to modify the config file so, I can use the numpad keys but, I don't know its names.

When I tried to use numbers like: 4, 6, 8, ...
It used the numbers row, not the numpad.

And I tried KP_num like: 
KP_4
KP_2
But didn't work.

How can I find keys name of the numpd ?

Thanks in advance.
The tool is great!.

**Comment by jbensmann** [comment]
Hi, it should be `kp4` etc., you can also use the `--debug` flag when running mouseless, press the key and look at the output.
