### ISSUE TITLE
config.yaml file not found

### ISSUE THREAD

**Issue by mdazizulbari** [jbensmann/mouseless#43]
I have the config.yaml file in the right place saved. But I am still getting this error.

mouseless.service - mouseless
     Loaded: loaded (/etc/systemd/system/mouseless.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sun 2023-12-31 10:01:45 +06; 14s ago
   Duration: 3ms
    Process: 7412 ExecStart=/usr/local/bin/mouseless --config ~/.config/mouseless/config.yaml (code=exited, status=1/FAILURE)
   Main PID: 7412 (code=exited, status=1/FAILURE)
        CPU: 4ms

Dec 31 10:01:45 smabari-A520MH-3-0 systemd[1]: Started mouseless.service - mouseless.
Dec 31 10:01:45 smabari-A520MH-3-0 mouseless[7412]: time="2023-12-31T10:01:45+06:00" level=error msg="Failed to read the config file: open ~/.config/museless/config.yaml: no such file or directory"
Dec 31 10:01:45 smabari-A520MH-3-0 mouseless[7412]: time="2023-12-31T10:01:45+06:00" level=error msg=Exiting
Dec 31 10:01:45 smabari-A520MH-3-0 systemd[1]: mouseless.service: Main process exited, code=exited, status=1/FAILURE
Dec 31 10:01:45 smabari-A520MH-3-0 systemd[1]: mouseless.service: Failed with result 'exit-code'.
![Screenshot from 2023-12-31 10-08-48](https://github.com/jbensmann/mouseless/assets/89230381/94883ade-89de-45e2-b9e8-4f2b61be5e3a)

**Comment by jbensmann** [comment]
I think the problem is that ´~/´ refers to the home directory of the root user in this case (usually ´/root´), one easy way to fix it is to write out the full path (´/home/someuser/.config/museless/config.yaml´).

**Comment by remembertoremind** [comment]
> one easy way to fix it is to write out the full path (`/home/someuser/.config/museless/config.yaml`).

However, do note that the path contains **mUse**less and not **mOUse**less.
