### ISSUE TITLE
insights on how to use with xremap

### ISSUE THREAD

**Issue by lefuturiste** [jbensmann/mouseless#45]
Hello,
I used to use [xmouseless](https://github.com/jbensmann/xmouseless) when I was on Xorg.
Now, I'm on wayland, I'm running [xremap](https://github.com/k0kubun/xremap) in background to have some neat shortcuts desktop-wide.
I would be interested if you could give some advices on how I could combine the two (mouseless + xremap).
I will be trying my self, and I probably will contribute to this program to add some options to fit it to my needs.
Thanks.

**Comment by jbensmann** [comment]
Hi and sorry for the late response,
I did not know about xremap but had a look, it works similar to mouseless by reading directly from the keyboard devices and creating a new device for the output. As two applications cannot read from the same device, xremap has to read from the device created by mouseless or the other way around, for the former you could start xremap with `--device=mouseless --watch=device`.
In case you also remap keys in mouseless, keep in mind that you have to consider those in xremap.
