### ISSUE TITLE
Send notification on config reload

### ISSUE THREAD

**Issue by limaceous-bushwhacker** [jbensmann/mouseless#56]
Is it possible to chain `reload-config` with `notify-send`?

**Comment by jbensmann** [comment]
Yes that should work with `multi`, e.g. `multi reload-config; exec notify-send "mouseless config reloaded"`.

**Comment by limaceous-bushwhacker** [comment]
Ah, thank you.

**Comment by oscarfv** [comment]
This doesn't work when executing mouseless as a root systemd service, does it? I tried

```
c: multi reload-config ; exec notify-send "mouseless config reloaded"
```

and

```
c: multi reload-config ; exec /usr/bin/notify-send "mouseless config reloaded"
```

In every case `sudo systemclt status mouseless.service` showed

```
level=warning msg="Execution of command failed: exit status 1"
```
