### ISSUE TITLE
Moving mouse pointer to absolute position

### ISSUE THREAD

**Issue by oscarfv** [jbensmann/mouseless#59]
I just discovered this little gem. Thank you very much for sharing it.

I'm trying to replace some xdotool invocations with the actions provided natively by mouseless. One of them is to move the mouse pointer to an absolute point of the screen. Started with this:

```
w: move -9999 -9999
```

It moves the pointer to the top left corner of the screen. So far so good. Then tried this:

```
w: multi move  -9999 -9999 ; move 100 0
```

It does nothing :-(.

I guess there are some problems with this approach: for starters, one thing is the numbers taken by the `move` action and another is the coordinates of the screen, they surely are different things. This is not a big deal because I can adjust the numbers until they are correct.

Second issue is that `mouseless` repeatedly issues `move` pseudo-inputs for as long as the key is pressed. This does not fit with what I want to do: "move this much to here and then that much to there".

So it is clear that I'm doing this wrong. My question is: is it possible to do what I want with current `mouseless`? If the answer is negative, is this an interesting feature for adding to `mouseless`?

**Comment by mashrit** [comment]
yes, i request this feature from the developer

**Comment by jbensmann** [comment]
This is currently not possible.

It might be possible by imitating a touch pad, but I cannot tell you if or when I will implement this, since there is not much benefit compared to calling an external tool like `xodotool` from mouseless.

**Comment by oscarfv** [comment]
> This is currently not possible.
> 
> It might be possible by imitating a touch pad, but I cannot tell you if or when I will implement this, since there is not much benefit compared to calling an external tool like `xodotool` from mouseless.

`xdotool` is what I'm using now, but the equivalent utility for Wayland is a bit problematic. A very nice thing about `mouseless` is that it does not depend on X or Wayland. Also, `mouseless` is super-fast, while calling an external utility sometimes incurs into a perceptible delay.

I was expecting for this feature to be not possible at all, but the touchpad emulation is interesting, I will look into it if I get annoyed enough while working with Wayland  :-)

Thank you.

**Comment by mashrit** [comment]
did you find any solutions?
