### ISSUE TITLE
Enabling two keyboard at the same time 

### ISSUE THREAD

**Issue by Bastien-mva** [jbensmann/mouseless#6]
Hello, 

Thanks for mouseless, it is great. 

I am getting a new split keyboard and as a result, my OS see 2 differents keyboard for the split keyboard. Do you know if I can change something in the ```config.yaml``` file so that it takes both keyboards ? Something like 

```
devices: 
- PATH/TO/KEYBOARD1
- PATH/TO/KEYBOARD2
``` 
Thanks :)

**Comment by jbensmann** [comment]
Hi, yes one can specify multiple devices like this, so it should work fine when you put in both devices.
