### ISSUE TITLE
Crash on start: "failed to create event loop"

### ISSUE THREAD

**Issue by neverix** [jbensmann/mouseless#68]
I reset the shortcuts for enabling the overlay (only setting the shortçut for the overlay) and saved the config to test. Ever since then, I couldn't start the app. In the command line, the `mouseless` executable prints:
```
Failed to create event tap
(...) +[IMKClient subclass]: chose IMKClient_Legacy
(...) +[IMKInputSession subclass]: chose IMKInputSession_Legacy
(...) <class 'KeyError'>: 'toggle overlay'
```

**Comment by mashrit** [comment]
can you send the config?

**Comment by neverix** [comment]
Sorry, wrong mouseless

**Comment by mashrit** [comment]
now you got me curious, what mouseless are you talking about?

**Comment by neverix** [comment]
https://mouseless.click
