### ISSUE TITLE
Mouseless making my keys slower

### ISSUE THREAD

**Issue by OzzSha** [jbensmann/mouseless#7]
i have set my keyboard to register key taps faster (xset r rate 250 35), but when i run mouseless, it gets reverted back to the default slower speed. Is there any way to fix this? Thanks :)

**Comment by jbensmann** [comment]
This is because mouseless basically creates a new keyboard to which the setting has to be applied again (same as when one plugs in a real keyboard). There is an option in the config file to execute commands after the mouseless keyboard has been created, like:
```
startCommand: "xset r rate 250 35"
```

**Comment by OzzSha** [comment]
Thanks a ton, that fixed my problem! And thanks for developing mouseless :) Have been looking for a good alternative for a while.

**Comment by jbensmann** [comment]
You're welcome :)

**Comment by serranomorante** [comment]
Ok, this works if I use the user setup instead of the root one (from the README)
